#!/bin/bash

# Submit this script with: sbatch submissionscript.sub

#SBATCH --time=12:00:00   # walltime
#SBATCH --ntasks=6   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=4G   # memory per CPU core
#SBATCH -J "gan_dft"   # job name
#SBATCH --mail-user=pkozlows@caltech.edu   # email address
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#Export env from shell (i.e. load modules etc)
#SBATCH --export=ALL 

## /SBATCH -p general # partition (queue)
## /SBATCH -o slurm.%N.%j.out # STDOUT
## /SBATCH -e slurm.%N.%j.err # STDERR

# load modules needed to run Python, activate appropriate Python venv, and run script
module load python3/3.11.4
source /central/groups/hadtlab/MJC/python-environments/pyCCE-env/bin/activate
python3 /groups/hadtlab/MJC/1OQR_WT/protein.py
deactivate
